#!/bin/bash

cd ~/HDD/workshop/OCW_assignments/

# cp ../study_material/60001/assignments_60001.ipynb 60001.ipynb
cp ../study_material/1806SC/1806SC_assignments.ipynb 1806SC.ipynb
cp ../study_material/60002/assignments.ipynb 60002.ipynb

git add /home/alex/HDD/workshop/OCW_assignments/.
git commit
git push origin master
